name: Deploy to Github pages
#on:
#  push:
#    branches: [ "create-deploy-qt-wasm-gh-pages" ]
on: workflow_dispatch

jobs:

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    
    - name : Checkout source code
      uses: actions/checkout@v3
      
    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.14
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '6.4.2'
        host: 'linux'
        target: 'desktop'
        arch: 'wasm_32'
        
    - name: Build the Qt6QuickApp to the build_wasm folder
      run:  cd Qt6QuickApp && mkdir -p build_wasm && cd build_wasm && qt-cmake .. && cmake --build .
