name: Deploy to Github pages Qt6WASMApp

on: workflow_dispatch

jobs:

  deploy-to-github-pages:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Install apt packages
      run: sudo apt update && sudo apt install cmake ninja-build
      
    - uses: actions/checkout@v3

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.14
        actions-cache-folder: 'emsdk-cache'
  
    - name: Install Qt WASM
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.1'
        version: '6.4.2'
        host: 'linux'
        target: 'desktop'
        arch: 'wasm_32'
        dir: '${{ github.workspace }}'
        cache: 'true'
        extra: '--autodesktop'
        py7zrversion: '>=0.20.2'
        
    - name: Build the Qt6QuickApp to the build_wasm folder
      run: |
         pwd 
         ls -alh .
         /usr/bin/cmake \
           --debug-output \
           -S Qt6QuickApp  \
           -B build-Qt6QuickApp-WebAssembly-Debug \
           -DCMAKE_BUILD_TYPE:STRING=Debug \
           -DCMAKE_PREFIX_PATH:PATH=/home/runner/work/dev-env-debian/dev-env-debian/Qt/6.4.2/wasm_32 \
           -DCMAKE_C_COMPILER:FILEPATH=/home/runner/work/dev-env-debian/dev-env-debian/emsdk-cache/emsdk-main/upstream/emscripten/emcc \
           -DCMAKE_CXX_COMPILER:FILEPATH=/home/runner/work/dev-env-debian/dev-env-debian/emsdk-cache/emsdk-main/upstream/emscripten/em++  \
           -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/home/runner/work/dev-env-debian/dev-env-debian/Qt/6.4.2/wasm_32/lib/cmake/Qt6/qt.toolchain.cmake \
           -DCMAKE_CXX_FLAGS_INIT:STRING=-DQT_QML_DEBUG \
           -DQT_HOST_PATH:PATH=/home/runner/work/dev-env-debian/dev-env-debian/Qt/6.4.2/gcc_64
         /usr/bin/cmake --build build-Qt6QuickApp-WebAssembly-Debug --target all
      shell: bash
           
    - name: uploade Artifacts 
      uses: actions/upload-artifact@v3
      with:
        name: build-Qt6QuickApp-WebAssembly-Debug
        path: build-Qt6QuickApp-WebAssembly-Debug
    
    - name : Commit build-Qt6QuickApp-WebAssembly-Debug to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build-Qt6QuickApp-WebAssembly-Debug # The folder the action should deploy.
        CLEAN: false # Automatically remove deleted files from the deploy branch
        TARGET_FOLDER : build-Qt6QuickApp-WebAssembly-Debug
